Isi2.Projekt/Isi2.Projekt.Web/Controllers/EntryController.cs
using Isi2.Projekt.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Isi2.Projekt.Web.Controllers
{
    public class EntryController : Controller
    {
        public ActionResult Index()
        {
            var items = new List<EntryContract>();

            for (int i = 0; i < 20; i++)
            {
                items.Add(new EntryContract { Id = 1, Title = "tytuł" + i, AuthorId = i, Created = DateTime.Now });
            }

            return View(items);
        }
    }
}

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Projekt</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-responsive.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <style type="text/css">
      #content {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div id="content">
        <section class="navbar navbar-inverse navbar-fixed-top">
          <div class="navbar-inner">
            <div class="container">
              @Html.Partial("_Menu")
            </div>
          </div>
        </section>

        <section class="container">
            <div class="row">
              <div id="inner">
                
                @RenderBody()
                  </div>
            </div>
        </section>
    </div>
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.6.2.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")" type="text/javascript"></script>
</body>
</html>

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated)
{
    <form class="navbar-form pull-right form-inline" action="@Url.Action("LogOff", "Account")" method="post">
        <label class="checkbox">
            zalogowano jako: <strong>@User.Identity.Name</strong>
        </label>
        <button type="submit" class="btn btn-danger">Wyloguj</button>
    </form>
    
}
else
{
    <form class="navbar-form pull-right" style="margin-left: 10px;" action="@Url.Action("Register", "Account")" method="get">
        <button type="submit" class="btn btn-info">Zarejestruj</button>
    </form>
    <form class="navbar-form pull-right" action="@Url.Action("LogOn", "Account")" method="post">
        <input class="span2" type="text" placeholder="Login" name="UserName" />
        <input class="span2" type="password" placeholder="Hasło" name="Password" />
        <button type="submit" class="btn btn-success">Zaloguj</button>
    </form>
}

Isi2.Projekt/Isi2.Projekt.Web/Views/Shared/_Menu.cshtml
@Html.ActionLink("Projekt", "Index", "Entry", null, new { @class = "brand" })

@{
    Func<string, string> IsActive = (link) =>
    {
        if (Request.RawUrl == link)
            return "active";
        return string.Empty;
    };
}

<nav class="nav-collapse collapse">
    <ul class="nav">
        <li class="@IsActive(@Url.Action("Index"))">
            <a href="@Url.Action("Index")"><i class="icon-home icon-white"></i>&nbsp;Najlepsze</a>
        </li>
        <li>
            <a href="#about"><i class="icon-th-large icon-white"></i>&nbsp;Poczekalnia</a>
        </li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-th icon-white"></i>&nbsp;Kategorie <b class="caret"></b></a>
            <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
            </ul>
        </li>
        @if (Request.IsAuthenticated)
        {
            <li><a href="#about"><i class="icon-star icon-white"></i>&nbsp;Ulubione</a></li>
            <li><a href="#about"><i class="icon-plus icon-white"></i>&nbsp;Dodaj</a></li>
            
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-user icon-white"></i>Panel użytkownika <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Edytuj profile</a></li>
                    <li><a href="/Account/ChangePassword">Zmiana hasła</a></li>
                </ul>
            </li>
        }
    </ul>
    @Html.Partial("_LogOnPartial")
</nav>